name: Build and Package Spring App with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Package Application
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK for Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the Spring Boot application
      - name: Build Application with Maven
        run: mvn clean test package

      # Step 5: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t notes-app-image:${{ github.sha }} .
